### ISSUE TITLE
تم تغيير رابط الـ API 

### ISSUE THREAD

**Issue by AhmedElTabarani** [mayman007/HadithSearcher#1]
السلام عليكم ورحمة الله وبركاته

آسف لكن حدثت مشكلة واضطررت لتغير الرابط
احد ما عمل request  لا نهائي تسبب في انتهاء الباقة المجانية ووقف الـ API

هذا الرابط الجديد
https://dorar-hadith-api.cyclic.cloud/

**Comment by AhmedElTabarani** [comment]
@Shinobi7k

**Comment by Shinobi7k** [comment]
شكرا لإعلامي صلحت المشكلة في آخر Release.

**Comment by MAymanKH** [comment]
شكرا لإعلامي, صلحت المشكلة في آخر Release.

**Comment by AhmedElTabarani** [comment]
@Shinobi7k 

أنا بفضل انك تعمل fork  أو clone للمشروع وترفعه على سيرفر او إستضافة خلص بيك 
علشان احتمال أنا أشيل الرابط خالص واخلي الناس ترفعه على سيرفهم الخاص بعد كدا لو عاوزين يستعملوه
علشان مش اقدر اخليه مرفوع للابد والتعامل مع كل الـ requests  دي في نفس الوقت

**Comment by MAymanKH** [comment]
@AhmedElTabarani 
شكرا للنصيحة
أنا عملت كدا خلاص وحدثت التطبيق
